import { RequiredDataFromCollectionSlug } from 'payload'

export const contactForm: RequiredDataFromCollectionSlug<'forms'> = {
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you for reaching out!',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Your message has been received. Our team will get back to you within 24 hours.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  createdAt: '2023-01-12T21:47:41.374Z',
  emails: [
    {
      emailFrom: '"RAG Platform" <support@ragbuilder.com>',
      emailTo: '{{email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Hello {{full-name}},',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: "Thank you for contacting the RAG Builder platform. We've received your inquiry and will respond shortly.",
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Best regards,',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'RAG Builder Support Team',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: "We've received your message - RAG Builder",
    },
  ],
  fields: [
    {
      name: 'full-name',
      blockName: 'full-name',
      blockType: 'text',
      label: 'Full Name',
      required: true,
      width: 50,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email',
      required: true,
      width: 50,
    },
    {
      name: 'company',
      blockName: 'company',
      blockType: 'text',
      label: 'Company',
      required: false,
      width: 50,
    },
    {
      name: 'reason',
      blockName: 'reason',
      blockType: 'select',
      label: 'Reason for Contact',
      required: true,
      width: 50,
      options: [
        {
          label: 'General Inquiry',
          value: 'general',
        },
        {
          label: 'Technical Support',
          value: 'support',
        },
        {
          label: 'Feature Request',
          value: 'feature',
        },
        {
          label: 'Partnership Opportunity',
          value: 'partnership',
        },
        {
          label: 'Other',
          value: 'other',
        },
      ],
    },
    {
      name: 'message',
      blockName: 'message',
      blockType: 'textarea',
      label: 'Message',
      required: true,
      width: 100,
    },
    {
      name: 'rag-experience',
      blockName: 'rag-experience',
      blockType: 'select',
      label: 'Experience with RAG applications',
      required: false,
      width: 100,
      options: [
        {
          label: 'Beginner - Just exploring',
          value: 'beginner',
        },
        {
          label: 'Intermediate - Built a few apps',
          value: 'intermediate',
        },
        {
          label: 'Advanced - Extensive implementation experience',
          value: 'advanced',
        },
        {
          label: 'Professional - Building RAG solutions for clients',
          value: 'professional',
        },
      ],
    },
    {
      name: 'privacy-consent',
      blockName: 'privacy-consent',
      blockType: 'checkbox',
      label: 'I agree to the privacy policy and consent to being contacted regarding my inquiry',
      required: true,
      width: 100,
    },
  ],
  redirect: undefined,
  submitButtonLabel: 'Send Message',
  title: 'Contact RAG Builder Support',
  updatedAt: '2023-01-12T21:47:41.374Z',
}
